apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1javaapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp-container
        image: venudoc98/myjavaapp06may22:3
        ports:
        - containerPort: 8080