apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavaapp-container
          image: maha4iac/mymahalogin02april22:1
          ports:
            - containerPort: 80 
