apiVersion: v1
kind: Service
metadata:
  name: mytomcat-svc
  labels:
    app: mytomcat    
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mytomcat 
    

