apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: mynginx
spec:
  type: NodePort
  ports: 
  - port: 80
    nodePort: 30002
    protocol: TCP
  spec:
    selector:
      app: mynginx  

