apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat-rc
spec:
  replicas: 3 
  selector:
    app: mytomcat
  template:
    metadata:
      labels:
        app: mytomcat
    spec:
      containers:
        - name: mytomcat
          image: tomcat:8.5.78
          ports:
            - containerPort: 8080


